using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MSGraphShield.Proxy.Exceptions.Models
{
    /// <summary>
    /// A machine-readable format for specifying errors in HTTP API responses based on RFC7807.
    /// </summary>
    [JsonConverter(typeof(ExceptionDetailsJsonConverter))]
    internal class ExceptionDetails
    {
        /// <summary>
        /// A URI reference that identifies the problem type. When dereferenced, it provides human-readable documentation for the problem type.
        /// </summary>
        [JsonPropertyName("type")]
        public string? Type { get; set; }

        /// <summary>
        /// A short, human-readable summary of the problem type.
        /// </summary>
        [JsonPropertyName("title")]
        public string? Title { get; set; }

        /// <summary>
        /// The HTTP status code generated by the origin server for this occurrence of the problem.
        /// </summary>
        [JsonPropertyName("status")]
        public int? Status { get; set; }

        /// <summary>
        /// A human-readable explanation specific to this occurrence of the problem.
        /// </summary>
        [JsonPropertyName("detail")]
        public string? Detail { get; set; }

        /// <summary>
        /// A URI reference that identifies the specific occurrence of the problem.
        /// </summary>
        [JsonPropertyName("instance")]
        public string? Instance { get; set; }

        /// <summary>
        /// Gets the dictionary for extension members.
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object?> Extensions { get; set; } = new Dictionary<string, object?>(StringComparer.Ordinal);

        /// <summary>
        /// Initializes a new instance of the <see cref="ExceptionDetails"/> class.
        /// </summary>
        public ExceptionDetails()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="ExceptionDetails"/> class using an <see cref="IProductException"/>.
        /// </summary>
        /// <param name="exception">The exception.</param>
        public ExceptionDetails(IProductException exception)
        {
            Type = exception.Type;
            Title = exception.Title;
            Status = exception.Status;
            Detail = exception.Message.Trim();
            Extensions = exception.Extensions;
        }
    }
}
