using System;
using System.Collections.Generic;

namespace GraphShield.Proxy.Exceptions.Models
{
    /// <summary>
    /// Represents a base class for product exceptions.
    /// </summary>
    internal class ProductException : Exception, IProductException
    {
        /// <summary>
        /// A URI reference that identifies the problem type.
        /// </summary>
        public string? Type { get; set; }

        /// <summary>
        /// A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence
        /// of the problem, except for purposes of localization(e.g., using proactive content negotiation;
        /// see[RFC7231], Section 3.4).
        /// </summary>
        public string? Title { get; set; }

        /// <summary>
        /// The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
        /// </summary>
        public int Status { get; set; }

        /// <summary>
        /// Gets the <see cref="IDictionary{TKey, TValue}"/> for extension members.
        /// <para>
        /// Problem type definitions MAY extend the problem details object with additional members. Extension members appear in the same namespace as
        /// other members of a problem type.
        /// </para>
        /// </summary>
        public IDictionary<string, object?> Extensions { get; set; } = new Dictionary<string, object?>(StringComparer.Ordinal);

        /// <summary>
        /// Gets a message that describes the current exception.
        /// </summary>
        public new string Message { get; set; }

        /// <summary>
        /// Gets a string representation of the immediate frames on the call stack.
        /// </summary>
        private readonly string? _stackTrace;

        /// <summary>
        /// Gets a string representation of the immediate frames on the call stack.
        /// </summary>
        public override string? StackTrace => _stackTrace;

        /// <summary>
        /// Initializes a new instance of the <see cref="ProductException"/> class.
        /// </summary>
        /// <param name="message">The error message.</param>
        public ProductException(string message)
        {
            Message = message;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProductException"/> class.
        /// </summary>
        /// <param name="exception">The exception that caused the product exception.</param>
        /// <param name="message">The error message.</param>
        public ProductException(Exception exception, string message)
        {
            Message = message;
            _stackTrace = exception.StackTrace;
        }
    }
}
