name: .NET Core

env:
  DOTNET_VERSION: '7.0.x' 

on:
  push:
    branches:
        - develop
        - beta
        - main
  pull_request:
    branches:
        - develop
        - beta
        - main

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Add dotnet-format problem matcher
        uses: xt0rted/dotnet-format-problem-matcher@v1

      - name: Restore dotnet tools
        uses: xt0rted/dotnet-tool-restore@v1

      - name: Run dotnet format (Pull Request)
        uses: xt0rted/dotnet-format@v1
        with:
          only-changed-files: "true"
        if: github.event_name == 'pull_request'

      - name: Run dotnet format (Push)
        uses: xt0rted/dotnet-format@v1
        with:
          fail-fast: "false"
        if: github.event_name == 'push'

      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: true

      - name: Set up dependency caching
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget
          restore-keys: ${{ runner.os }}-nuget

      - name: Build Solution
        run: dotnet build GraphShield.sln
