name: .NET Core

env:
  DOTNET_VERSION: '7.0.x' 

on:
  push:
    branches:
        - develop
        - beta
        - main
  pull_request:
    branches:
        - develop
        - beta
        - main

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: true

      - name: Set up dependency caching
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget
          restore-keys: ${{ runner.os }}-nuget

      - name: Build Solution
        run: dotnet build MSGraphShield.sln
